// Leave List
export const LEAVE_LIST_REQUEST = 'LEAVE_LIST_REQUEST'
export const LEAVE_LIST_SUCCESS = 'LEAVE_LIST_SUCCESS'
export const LEAVE_LIST_FAIL = 'LEAVE_LIST_FAIL'
export const LEAVE_LIST_RESET = 'LEAVE_LIST_RESET'

// My leave List
export const LEAVE_LIST_MY_REQUEST = 'LEAVE_LIST_MY_REQUEST'
export const LEAVE_LIST_MY_SUCCESS = 'LEAVE_LIST_MY_SUCCESS'
export const LEAVE_LIST_MY_FAIL = 'LEAVE_LIST_MY_FAIL'
export const LEAVE_LIST_MY_RESET = 'LEAVE_LIST_MY_RESET'

// Register
export const LEAVE_CREATE_REQUEST = 'LEAVE_CREATE_REQUEST'
export const LEAVE_CREATE_SUCCESS = 'LEAVE_CREATE_SUCCESS'
export const LEAVE_CREATE_FAIL = 'LEAVE_CREATE_FAIL'
export const LEAVE_CREATE_RESET = 'LEAVE_CREATE_RESET'

// Leave Details
export const LEAVE_DETAILS_REQUEST = 'LEAVE_DETAILS_REQUEST'
export const LEAVE_DETAILS_SUCCESS = 'LEAVE_DETAILS_SUCCESS'
export const LEAVE_DETAILS_FAIL = 'LEAVE_DETAILS_FAIL'
